FROM java:8
MAINTAINER javaonfly
COPY /KarthickTravelOnline/target/KarthickTravelOnline-0.0.1-SNAPSHOT.jar KarthickTravelOnline-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "KarthickTravelOnline-0.0.1-SNAPSHOT.jar"]
EXPOSE 8091
